services:
  # WordPress with PHP-FPM
  wordpress:
    build:
      context: ./requirements/wordpress
    env_file:
      ../.env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - wordpress_network
    restart: always

  # MariaDB Database
  db:
    build:
      context: ./requirements/mariadb
    env_file:
      ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ADMIN_USER: ${MARIADB_ADMIN_USER}
      MARIADB_ADMIN_PASSWORD: ${MARIADB_ADMIN_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    restart: always

  # NGINX Reverse Proxy
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wordpress_network
    restart: always

  # BONUS

  # Redis Cache
  redis:
    build:
      context: ./bonus/redis
    container_name: redis
    networks:
      - wordpress_network
    restart: always

  # FTP Server
  ftp:
    build:
      context: ./bonus/ftp
    container_name: ftp
    env_file:
      ../.env
    volumes:
      - /home/jeandrad/data/wordpress:/var/www/html
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - wordpress_network
    restart: always
    profiles:
      - bonus

  # Static Website
  static_site:
    build:
      context: ./bonus/static-site
    container_name: static_site
    networks:
      - wordpress_network
    restart: always
    profiles:
      - bonus

  # Adminer
  adminer:
    build:
      context: ./bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - wordpress_network
    restart: always
    profiles:
      - bonus

  # Portainer
  portainer:
    build:
      context: ./bonus/portainer
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - wordpress_network
    restart: always
    profiles:
      - bonus

# Volumes for persistent data storage
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jeandrad/data/wordpress'
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jeandrad/data/mariadb'
  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jeandrad/data/portainer'

# Networks for secure communication
networks:
  wordpress_network:
    driver: bridge
